### ISSUE TITLE
slash in FROM line

### ISSUE THREAD

**Issue by TomasTomecek** [bkabrda/container-image-template-dfe#2]
`FROM {{ base_img_reg }}/`

I'm still thinking about this one. Yes, we can set `base_img_reg = docker.io`, but we can also set it to `''`, which should be valid but I believe that one will blow.

**Comment by bkabrda** [comment]
Hmm, yes... we could make `dfe` add the slash to `base_img_reg` if it's present and non-empty string. This would both avoid crazy conditionals in the template and would be comfortable for writing configurations.
